[project]
name = "calhacks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "flask>=3.1.2",
    "openai>=2.6.1",
    "flask-cors (>=6.0.1,<7.0.0)",
]
