[package]
name = "rust-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
imessage-database = "3.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"] }
